### ISSUE TITLE
Error, when run MultiMaterialLiquids.

### ISSUE THREAD

**Issue by goofoo** [rgoldade/2DFluid#1]
Hi Ryan. 
When try run example "MultiMaterialLiquids" and press "m" - program crushed with error:
MultiMaterialLiquids: /home/goofoo/2dFluid/Projects/Simulations/Library/MultiMaterialPressureProjection.cpp:81: MultiMaterialPressureProjection::project(const std::vector<VectorGrid<double> >&, const VectorGrid<double>&)::<lambda(const Vec2i&)>: Assertion `mySolidSurface(cell) <= 0' failed.
Aborted (core dumped)
And, when compile code, cmake exit with error: not folder "2DConstraintBubble" add_subdirectory(2DConstraintBubble).

Linux Mint 19, 2x xeon e5-2670
Thanks.

**Comment by rgoldade** [comment]
I will look into it. Thank you for bringing this issue forward.

**Comment by rgoldade** [comment]
I updated a lot of the code. Let me know if you still have a problem with the multi material simulation.
