### ISSUE TITLE
Narrow band flip

### ISSUE THREAD

**Issue by goofoo** [rgoldade/2DFluid#3]
Hi. How about add implementation narrow band flip?
Thanks.

**Comment by rgoldade** [comment]
At the moment there isn't any implementation of a FLIP simulation at all. Everything uses meshes and level sets. There is limited support for marker particles that can be extended to FLIP. I've mostly used this project for research prototyping so level sets are good enough. It's possible in the future that I will add proper FLIP support. If so, I will consider including narrow band.
